name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "n"
  comment: "Android Studio for Windows"
  url: "https://res06.bignox.com/full/20240418/302ea2e2c5284db68e5494d3e7989c0c.exe?filename=nox_setup_v7.0.6.0_full_intl.exe"
  file_name: "nox_setup_v7.0.6.0_full_intl.exe"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
