name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "c"
  comment: "Android Studio for Windows"
  url: "https://download193.uploadhaven.com/1/application/zip/2XELJM944VGzkqNVGQwCBIsRnowHuLXXmrAvyqcC.zip?key=uWMmNc-bT7T4nOLdkG0P7w&expire=1722775522&filename=Celeste.v1.4.0.0.zip"
  file_name: "Celeste.v1.4.0.0.zip"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
