name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ctr1"
  comment: "Android Studio for Windows"
  url: "https://dw.uptodown.net/dwn/4oxNb1Lgr9q4yiggE8LT2ZhQrrrHH1gADrRppItOhE9jZJihw6R0yEb6dR_UvhGUEArHREF6VxxWbP8cWhgAoO5l-fo6lVVXURAPXaE7KRBTeyOlCLhYZ4MM0Ih70vHy/Xbfe7RuO-_DLL9PXSo_IYiW05zC9rNFWS8iYUP3tSIFSJdxDiyzF7T19yfBhcvbXigYvvJaphq0yu8i4wStBeCeeFaEqPuqluKKhTVSo1wbQrCnKMS7uZXC1BdWX3cA7/9zlGvrXOjzxJhDXoMJD2CaDAJupbpobmYvJOP6BK2sSv1GJruorOADvE4WaFKH4e2u00KLtig_if6EmCk3uo5w==/cut-the-rope-3-65-0.apk"
  file_name: "cut-the-rope-3-65-0.apk"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
