name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "pvz2apk"
  comment: "Android Studio for Windows"
  url: "https://srv003.apk.gold/storage/17/639/2639/arm64_v8a-armeabi_v7a/cfa0c5b974cfd2f960d86ab63364214d/Plants_Vs_Zombies_2-11.3.1.apk?s=wx5CUt_QiEff1tzdZjcnJw&e=1716715050&lang=en&apk_id=2618"
  file_name: "Plants_Vs_Zombies_2-11.3.1.apk"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
