name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ge"
  comment: "Android Studio for Windows"
  url: "https://objects.githubusercontent.com/github-production-release-asset-2e65be/15634981/6b875bf5-9230-4850-bc4b-4de978817b22?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240605%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240605T085707Z&X-Amz-Expires=300&X-Amz-Signature=ee3ee8905667f4f708d621294ba95bfd1be7dfd48d13af542f7f1e449f40edf9&X-Amz-SignedHeaders=host&actor_id=94167570&key_id=0&repo_id=15634981&response-content-disposition=attachment%3B%20filename%3DGodot_v4.2.2-stable_win64.exe.zip&response-content-type=application%2Foctet-stream"
  file_name: "Godot_v4.2.2-stable_win64.exe.zip"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
