name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ab2obb"
  comment: "Android Studio for Windows"
  url: "https://srv003.apk.gold/storage/17/142/4142/com.rovio.baba-3.22.1-31882466.obb?s=KsudBv15ynipqsOTXvgAew&e=1716714995&lang=en&apk_id=1270&obb_id=34959"
  file_name: "com.rovio.baba-3.22.1-31882466.obb"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
