name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "godotapk"
  comment: "Android Studio for Windows"
  url: "https://objects.githubusercontent.com/github-production-release-asset-2e65be/15634981/eb63ec7f-6d7a-4fbb-b470-bb4b616428b2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240712T125235Z&X-Amz-Expires=300&X-Amz-Signature=4831a846b96b9dc6a1c486404a91f41d8eafb8ae7b2d97fb5e91c126dd954c94&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=15634981&response-content-disposition=attachment%3B%20filename%3DGodot_v4.2.2-stable_android_editor.apk&response-content-type=application%2Fvnd.android.package-archive"
  file_name: "Godot_v4.2.2-stable_android_editor.apk"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
