name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "godotapk"
  comment: "Android Studio for Windows"
  url: "https://cdn.androidcombo.com/org.godotengine.editor.v4/Godot%20Editor%204_4.2.2.stable_apkcombo.com.apk?ecp=b3JnLmdvZG90ZW5naW5lLmVkaXRvci52NC80LjIuMi5zdGFibGUvNDAyMDI1MDAuZDY5Zjc0OWFmZTc2ZWRlM2E1YzMzYzM1ZTdmZTZlZWIzOGMyOTQ3Ni5hcGs%3D&iat=1720789728&sig=570bf792a60275eb299cb414ed1121d5&size=179160384&from=cf&version=latest&lang=en&fp=7baafd7bc4ec2c86dba281cea8e2b1e9&ip=94.47.128.190"
  file_name: "Godot Editor 4_4.2.2.stable_apkcombo.com.apk"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
